apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: projecthub-backend
data:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.projecthub-database.svc.cluster.local:3306/project_db"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  SERVER_PORT: "8080"
